# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fundamental Inc.
email: contato@ifundamental.com.br
description: Fundamental Inc. é uma empresa criada para solucionar problemas utilizando sites, softwares e aplicativos. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fundamental.digital" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Gems

gems: [jekyll-paginate, jekyll-sitemap]
